import 'dart:async';
import 'dart:convert';
import 'dart:io';
import '../models/board_state.dart';
import '../models/scooter_health.dart';
import '../models/trampoline_status.dart';
import 'device_probe.dart';
import 'package:dartssh2/dartssh2.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:pointycastle/export.dart' as pc;
import 'package:yaml/yaml.dart';
import 'package:path/path.dart' as path;

/// SSH connection info for a device
class DeviceInfo {
  final String host;
  final String firmwareVersion;
  final String? serialNumber;

  /// Value of ID= in /etc/os-release if known (e.g. 'librescoot-mdb').
  /// Used to distinguish Librescoot from stock when version numbers collide.
  final String? osId;

  DeviceInfo({
    required this.host,
    required this.firmwareVersion,
    this.serialNumber,
    this.osId,
  });
}

/// Callback used to obtain a manually-entered root password when neither the
/// empty password nor the bundled device-config credential authenticates.
/// [version] is the firmware version we believe the device is running (or
/// null if undetectable). [previousAttempts] is how many manual passwords
/// have already been tried this session. Return null/empty string to give up.
typedef ManualPasswordPrompt =
    Future<String?> Function({
      required String? version,
      required int previousAttempts,
    });

/// Service for SSH communication with MDB/DBC devices
class SshService {
  static const String mdbHost = '192.168.7.1';
  static const String dbcHost = '192.168.7.2';
  static const int sshPort = 22;
  static const String sshUser = 'root';
  /// Short on purpose. An attempt already in flight against an unreachable
  /// host cannot notice the host arriving, so a long timeout is a window in
  /// which a board that comes back is missed. On the local USB link a healthy
  /// connect completes in well under a second, so this only bounds failures,
  /// and the caller retries: shorter attempts more often cover a transient
  /// window strictly better than long ones for the same wall clock.
  static const Duration connectionTimeout = Duration(seconds: 5);
  static const int maxManualPasswordAttempts = 3;

  @visibleForTesting
  static const interruptedInstallDisarmCommand = r'''
set -eu
scripts=/data/installer/scripts
backup=/data/installer/onboot.sh.bak
onboot=/data/onboot.sh
shim='Installed by the Librescoot installer'
marker='Auto-generated by installer trampoline'

# The phases an abandoned run left queued. The coordinator would run them on
# the next boot, against a staging directory this installer is about to reuse.
rm -f "$scripts"/[0-9][0-9]-*.sh "$scripts"/[0-9][0-9]-*.sh.tries

# Installers before the coordinator wrote the post-reboot half straight to
# /data/onboot.sh, so a board one of those touched carries it there instead.
if [ -f "$onboot" ] && grep -Fq "$marker" "$onboot"; then
  rm -f "$onboot"
fi
rm -f /data/installer/onboot-tries

# Retire the coordinator here rather than leaving it for a boot to notice, and
# give back a user's own onboot.sh if it displaced one. A resumed run installs
# it again before it queues anything.
if [ -f "$onboot" ] && grep -Fq "$shim" "$onboot"; then
  if [ -f "$backup" ]; then
    mv -f "$backup" "$onboot"
  else
    rm -f "$onboot"
  fi
fi

# Service mode belongs to settings-service, and a run that armed it and then
# died leaves it armed on every boot from here on: no hibernation timer, no
# alarm, handlebar unlocked. Removing the file is the whole disarm.
#
# The live overlay is deliberately left alone. It is what is holding usb0 up
# for the session running this, and clearing it here would drop the link on a
# board whose keycards are already paired. A resumed run arms it again before
# its own reboot; an abandoned one no longer survives the next one.
rm -f /data/service-mode.json

for phase in "$scripts"/[0-9][0-9]-*.sh; do
  [ -e "$phase" ] || continue
  echo 'installer phases are still armed' >&2
  exit 1
done
if [ -f "$onboot" ] && grep -Fq "$marker" "$onboot"; then
  echo 'a legacy installer onboot script is still armed' >&2
  exit 1
fi
if [ -e /data/installer/onboot-tries ]; then
  echo 'the legacy onboot retry counter still exists' >&2
  exit 1
fi
if [ -e /data/service-mode.json ]; then
  echo 'service mode is still armed' >&2
  exit 1
fi
''';

  /// Librescoot units only, and deliberately. This recovers a board an earlier
  /// install left masked, which is a state only a Librescoot board reaches: a
  /// stock board is one this installer has not touched yet.
  ///
  /// Unit names, not binary names. Librescoot ships `librescoot-<x>` units
  /// running `<x>-service` binaries, so `keycard-service` matched nothing here
  /// and never could.
  @visibleForTesting
  static const interruptedInstallServiceRecoveryCommand = r'''
set -eu
units='librescoot-keycard librescoot-bluetooth librescoot-ums'
systemctl unmask $units >/dev/null 2>&1 || true
systemctl start librescoot-bluetooth
systemctl start librescoot-ums

if [ "$(systemctl show -p LoadState --value librescoot-keycard 2>/dev/null || true)" = loaded ]; then
  systemctl start librescoot-keycard
fi

for unit in $units; do
  load_state=$(systemctl show -p LoadState --value "$unit" 2>/dev/null || true)
  if [ "$load_state" = not-found ] || [ -z "$load_state" ]; then
    continue
  fi
  enabled_state=$(systemctl is-enabled "$unit" 2>/dev/null || true)
  if [ "$enabled_state" = masked ]; then
    echo "$unit is still masked" >&2
    exit 1
  fi
done

for unit in librescoot-bluetooth librescoot-ums; do
  if ! systemctl is-active --quiet "$unit"; then
    echo "$unit is not active" >&2
    exit 1
  fi
done
''';

  /// Retries for a connection that dies before authentication ever happens.
  /// Doubling from one second, so the ladder spans about a minute: longer than
  /// any reboot this installer performs takes to bring sshd back.
  static const int maxPreAuthRetries = 15;

  /// Delay between attempts after a pre-auth drop.
  ///
  /// Constant, not a backoff. A pre-auth drop is a board whose sshd is
  /// listening before the system can authenticate, which is the ordinary state
  /// of every board this talks to for the first minute after a reboot. Backing
  /// off protects a server that is loaded, rate limiting or hostile, and this
  /// is a known device on a private link with nothing else on it. Doubling to
  /// 32 seconds meant the board could be ready for half a minute before anyone
  /// asked. A genuine auth failure is a different branch and does not come
  /// here.
  static const Duration preAuthRetryDelay = Duration(seconds: 2);

  /// Whether a failure hit the transport rather than the credential.
  ///
  /// dartssh2 raises [SSHAuthAbortError] when the connection closes before
  /// authentication completes, which is what sshd looks like in the seconds
  /// after a reboot. It arrives on the same path as a genuine rejection, so
  /// the two have to be told apart before the credential ladder advances.
  @visibleForTesting
  static bool isPreAuthDrop(Object e) {
    if (e is SSHAuthAbortError) return true;
    if (e is SocketException) return true;
    if (e is TimeoutException) return true;
    final text = e.toString();
    return text.contains('Connection closed before authentication') ||
        text.contains('Connection reset') ||
        text.contains('Software caused connection abort');
  }

  @visibleForTesting
  static Future<T> executeWithReplayPolicy<T>({
    required Future<T> Function() execute,
    required Future<void> Function() reconnect,
    required void Function() invalidateConnection,
    required bool Function(Object error) isDisconnect,
    bool replayOnDisconnect = false,
  }) async {
    try {
      return await execute();
    } catch (error) {
      if (!isDisconnect(error)) rethrow;
      invalidateConnection();
      if (!replayOnDisconnect) rethrow;
      await reconnect();
      try {
        return await execute();
      } catch (replayError) {
        if (isDisconnect(replayError)) invalidateConnection();
        rethrow;
      }
    }
  }

  SSHClient? _client;
  Map<String, String>? _deviceConfig;
  bool _sftpAvailable = false;

  /// How long the SFTP capability probe waits for a subsystem that may never
  /// answer. Short: a working one responds immediately, and the fallback is
  /// always available, so this is paid only to learn that it is needed.
  static const Duration sftpProbeTimeout = Duration(seconds: 8);
  ManualPasswordPrompt? _manualPasswordPrompt;

  // Snapshot of the last successful auth so we can silently re-establish the
  // session if the underlying socket dies (e.g. USB cable wiggle during a
  // poll loop). Cleared by [disconnect] so reboot paths don't auto-reconnect
  // before the device is back.
  String _lastHost = mdbHost;
  String? _lastPassword;
  Future<void>? _reconnectInFlight;
  int _redisQueueSequence = 0;

  /// Auth key injected at build time via --dart-define=AUTH_KEY=...
  static const _authKey = String.fromEnvironment('AUTH_KEY');

  /// Load device configuration from encrypted or plaintext asset.
  Future<void> loadDeviceConfig(String assetsPath) async {
    String yamlContent;

    if (_authKey.isNotEmpty) {
      try {
        final data = await rootBundle.load('$assetsPath/device_configs.bin');
        debugPrint('SSH: loading device profile (bundle)');
        yamlContent = _decryptAsset(
          data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
        );
      } catch (_) {
        final encFile = File(path.join(assetsPath, 'device_configs.bin'));
        if (await encFile.exists()) {
          debugPrint('SSH: loading device profile (filesystem)');
          yamlContent = _decryptAsset(await encFile.readAsBytes());
        } else {
          yamlContent = '';
        }
      }
    } else {
      yamlContent = '';
    }

    if (yamlContent.isEmpty) {
      final plainFile = File(path.join(assetsPath, 'device_configs.yml'));
      if (await plainFile.exists()) {
        debugPrint('SSH: loading device profile (dev fallback)');
        yamlContent = await plainFile.readAsString();
      } else {
        debugPrint('SSH: no device profile available, will use defaults');
        _deviceConfig = {};
        return;
      }
    }

    final yaml = loadYaml(yamlContent) as YamlMap;
    _deviceConfig = {};
    for (final entry in yaml.entries) {
      final version = entry.key.toString();
      final encoded = entry.value.toString();
      final decodedRaw = utf8.decode(base64.decode(encoded));
      _deviceConfig![version] = decodedRaw.trim();
    }
    debugPrint('SSH: device profile loaded (${_deviceConfig!.length} entries)');
  }

  /// Decrypt AES-256-CBC with IV prepended, PKCS7 padding.
  String _decryptAsset(Uint8List encrypted) {
    final keyBytes = Uint8List.fromList(
      utf8.encode(_authKey).take(32).toList()
        ..addAll(List.filled(32 - _authKey.length.clamp(0, 32), 0)),
    );
    final iv = encrypted.sublist(0, 16);
    final ciphertext = encrypted.sublist(16);

    final cipher = pc.CBCBlockCipher(pc.AESEngine())
      ..init(false, pc.ParametersWithIV(pc.KeyParameter(keyBytes), iv));

    final padded = Uint8List(ciphertext.length);
    var offset = 0;
    while (offset < ciphertext.length) {
      offset += cipher.processBlock(ciphertext, offset, padded, offset);
    }

    // Remove PKCS7 padding
    final padLen = padded.last;
    final unpadded = padded.sublist(0, padded.length - padLen);

    return utf8.decode(unpadded);
  }

  /// Set a callback to be invoked when the bundled credentials don't work
  /// and we need to ask the user for the root password. Only the initial
  /// MDB connect on stock firmware needs this: once Librescoot is flashed
  /// the password is empty.
  void setManualPasswordPrompt(ManualPasswordPrompt? prompt) {
    _manualPasswordPrompt = prompt;
  }

  /// Connect to MDB and detect firmware version
  Future<DeviceInfo> connectToMdb() async {
    final info = await _connect(mdbHost);
    // The MDB has no reliable RTC, so its clock (and every log timestamp)
    // drifts to nonsense across power cycles. Push the host's wall-clock time
    // and timezone in now that we have a shell. Best-effort, never fatal.
    await syncDeviceTime();
    return info;
  }

  /// Set the connected device's clock + timezone from this host. Best-effort:
  /// failures are logged and swallowed so a missing `hwclock`/`timedatectl`
  /// never blocks the install.
  Future<void> syncDeviceTime() async {
    if (_client == null) return;
    try {
      final utc = DateTime.now().toUtc();
      String two(int v) => v.toString().padLeft(2, '0');
      final stamp =
          '${utc.year.toString().padLeft(4, '0')}-${two(utc.month)}-${two(utc.day)} '
          '${two(utc.hour)}:${two(utc.minute)}:${two(utc.second)}';
      final tz = _hostTimezone();
      final cmds = <String>[];
      if (tz != null) {
        cmds.add(
          'timedatectl set-timezone $tz 2>/dev/null || ln -sf /usr/share/zoneinfo/$tz /etc/localtime 2>/dev/null || true',
        );
      }
      // -u: interpret the stamp as UTC, independent of the device's timezone.
      cmds.add('date -u -s "$stamp" >/dev/null 2>&1 || true');
      cmds.add('hwclock -w -u 2>/dev/null || true');
      // 60s, not 15: a freshly flashed board is busy on its first boot and
      // has been seen taking a minute just to offer SFTP. A clock that is
      // wrong on a board about to write date-stamped logs is worth waiting
      // for, and this is best-effort anyway.
      await runCommand(cmds.join('; '), timeout: const Duration(seconds: 60));
      debugPrint(
        'SSH: synced device time to ${stamp}Z, tz=${tz ?? '(unknown)'}',
      );
    } catch (e) {
      debugPrint('SSH: device time sync failed (non-fatal): $e');
    }
  }

  /// Best-effort IANA timezone of this host (e.g. "Europe/Berlin"), read from
  /// the /etc/localtime symlink. Returns null on Windows or if undeterminable.
  String? _hostTimezone() {
    try {
      if (Platform.isWindows) return null;
      final link = Link('/etc/localtime');
      if (link.existsSync()) {
        final target = link.targetSync();
        const marker = 'zoneinfo/';
        final i = target.indexOf(marker);
        if (i >= 0) {
          final tz = target.substring(i + marker.length);
          if (tz.isNotEmpty && !tz.contains(' ')) return tz;
        }
      }
    } catch (_) {}
    return null;
  }

  /// Connect to DBC via MDB jump host
  Future<DeviceInfo> connectToDbc() async {
    // First ensure we're connected to MDB
    if (_client == null) {
      await connectToMdb();
    }

    // Connect to DBC through MDB
    return _connect(dbcHost);
  }

  Future<DeviceInfo> _connect(String host) async {
    // Auth strategy:
    //   1. empty password (Librescoot)
    //   2. bundled credential matched against banner version (stock OS)
    //   3. user-supplied password via manual prompt callback (unknown stock)
    var authVersion = 'v1.20';
    var stage = 0; // 0 = empty, 1 = bundled, 2 = manual
    var manualAttempts = 0;
    var preAuthRetries = 0;
    String? manualPassword;

    while (true) {
      final socket = await SSHSocket.connect(
        host,
        sshPort,
        timeout: connectionTimeout,
      );
      debugPrint('SSH: connected socket to $host:$sshPort');

      var bannerVersionSeen = authVersion;
      String? attemptedPassword;
      _client = SSHClient(
        socket,
        username: sshUser,
        // Idle for minutes at a time while the user pairs a phone or teaches
        // in keycards; without this the far end can drop the session and the
        // next command fails for no visible reason.
        keepAliveInterval: const Duration(seconds: 5),
        onPasswordRequest: () {
          String pw;
          if (stage == 0) {
            debugPrint('SSH: attempting default device configuration');
            pw = '';
          } else if (stage == 1) {
            // Stage 0 already verified this version has a non-empty bundled
            // credential before transitioning here.
            pw = _resolveDeviceCredential(authVersion);
            debugPrint(
              'SSH: attempting bundled device configuration for version $authVersion',
            );
          } else {
            debugPrint(
              'SSH: attempting user-supplied configuration (attempt $manualAttempts)',
            );
            pw = manualPassword ?? '';
          }
          attemptedPassword = pw;
          return pw;
        },
        onUserauthBanner: (banner) {
          final bannerVersion = _extractVersionFromText(banner);
          if (bannerVersion != null) {
            bannerVersionSeen = bannerVersion;
            authVersion = bannerVersion;
            debugPrint('SSH: parsed version from banner -> $authVersion');
          }
        },
      );

      try {
        // dartssh2 completes this when the handshake finishes and never if the
        // far end accepts the socket and then says nothing. Without a bound
        // that is an unrecoverable hang rather than a failure: the retry below
        // only sees exceptions, so a stalled handshake never reaches it and
        // the screen sits on "reconnecting" for as long as anyone waits.
        await _client!.authenticated.timeout(connectionTimeout);
        debugPrint('SSH: authentication successful');
        _lastHost = host;
        _lastPassword = attemptedPassword ?? '';
        break;
      } catch (e) {
        debugPrint('SSH: authentication failed: $e');
        _client?.close();
        _client = null;

        // Not a rejected credential: a host that is not answering yet. Hold
        // the stage and the password where they are and come back.
        if (isPreAuthDrop(e) && preAuthRetries < maxPreAuthRetries) {
          preAuthRetries++;
          debugPrint(
            'SSH: dropped before authentication, retry '
            '$preAuthRetries/$maxPreAuthRetries in '
            '${preAuthRetryDelay.inSeconds}s',
          );
          await Future.delayed(preAuthRetryDelay);
          continue;
        }

        if (stage == 0) {
          if (bannerVersionSeen != 'v1.20') {
            authVersion = bannerVersionSeen;
            // Skip stage 1 if the bundled lookup would just return empty
            // (which we already tried) or has no entry at all.
            String? bundled;
            try {
              bundled = _resolveDeviceCredential(authVersion);
            } catch (_) {
              bundled = null;
            }
            if (bundled != null && bundled.isNotEmpty) {
              stage = 1;
              debugPrint(
                'SSH: default configuration not accepted, attempting bundled device configuration for $authVersion',
              );
              continue;
            }
            debugPrint(
              'SSH: no bundled device configuration for $authVersion, prompting user',
            );
          }
          stage = 2;
        } else if (stage == 1) {
          stage = 2;
        }

        if (stage == 2 &&
            _manualPasswordPrompt != null &&
            manualAttempts < maxManualPasswordAttempts) {
          final entered = await _manualPasswordPrompt!(
            version: bannerVersionSeen != 'v1.20' ? bannerVersionSeen : null,
            previousAttempts: manualAttempts,
          );
          if (entered == null || entered.isEmpty) {
            debugPrint('SSH: user cancelled manual configuration prompt');
            rethrow;
          }
          manualPassword = entered;
          manualAttempts++;
          debugPrint(
            'SSH: retrying with user-supplied configuration (attempt $manualAttempts)',
          );
          continue;
        }

        rethrow;
      }
    }

    // Stop power manager to prevent suspend/hibernate during flashing
    try {
      await runCommand(
        'systemctl stop librescoot-pm 2>/dev/null; '
        'systemctl stop unu-pm 2>/dev/null; true',
      );
      debugPrint('SSH: stopped power manager');
    } catch (_) {}

    final detected = await _detectFirmwareVersion();
    if (detected.version != null) {
      authVersion = detected.version!;
      debugPrint(
        'SSH: detected firmware version ${detected.version}'
        '${detected.osId != null ? " (os-id=${detected.osId})" : ""}',
      );
    } else {
      debugPrint(
        'SSH: firmware version detection failed, using Unknown for UI',
      );
    }

    // Stock runs dropbear, which has no working sftp subsystem, and os-release
    // has just told us which distribution this is. Skipping the probe outright
    // is better than probing well: the answer is already known and the probe
    // costs a timeout to reach it.
    final osId = detected.osId ?? '';
    if (osId.isNotEmpty && !osId.startsWith('librescoot')) {
      _sftpAvailable = false;
      debugPrint('SSH: os-release ID "$osId", uploads will use cat');
    } else {
      // Write something, do not just open a session. Neither the sftp-server
      // binary being on disk nor a session opening says the subsystem works:
      // dropbear opens one and then never completes a write, so an
      // open-and-close probe reported available and every upload afterwards
      // spent its full timeout discovering otherwise.
      //
      // A few bytes to /tmp is the smallest operation that exercises the thing
      // that actually fails, and the file is removed on the way out.
      try {
        final sftp = await _requireClient(
          'SFTP probe',
        ).sftp().timeout(sftpProbeTimeout);
        try {
          const probePath = '/tmp/.installer-sftp-probe';
          final file = await sftp
              .open(
                probePath,
                mode:
                    SftpFileOpenMode.write |
                    SftpFileOpenMode.create |
                    SftpFileOpenMode.truncate,
              )
              .timeout(sftpProbeTimeout);
          try {
            await file
                .write(Stream.value(Uint8List.fromList([0x6f, 0x6b])))
                .done
                .timeout(sftpProbeTimeout);
          } finally {
            await file.close();
          }
          await sftp.remove(probePath).timeout(sftpProbeTimeout);
          _sftpAvailable = true;
          debugPrint('SSH: SFTP available');
        } finally {
          sftp.close();
        }
      } catch (e) {
        _sftpAvailable = false;
        debugPrint('SSH: SFTP not available ($e), uploads will use cat');
      }
    }

    // Get serial number
    String? serial;
    try {
      // OCOTP UID is (CFG1 << 32) | CFG0 — high word first when concatenated.
      // fsl_otp is the NXP vendor driver (stock 4.x and librescoot 5.4
      // kernels); mainline kernels (1.2.0+ MDBs on linux-fslc 6.12) expose
      // the same value preformatted at /sys/devices/soc0/serial_number.
      final result = await runCommand(
        'cat /sys/fsl_otp/HW_OCOTP_CFG1 /sys/fsl_otp/HW_OCOTP_CFG0 2>/dev/null'
        ' || cat /sys/devices/soc0/serial_number 2>/dev/null',
      );
      serial = _parseSerial(result);
      if (serial != null) {
        debugPrint('SSH: parsed serial $serial');
      }
    } catch (e) {
      debugPrint('SSH: serial read failed: $e');
    }

    return DeviceInfo(
      host: host,
      firmwareVersion: detected.version ?? 'Unknown',
      serialNumber: serial,
      osId: detected.osId,
    );
  }

  Future<({String? version, String? osId})> _detectFirmwareVersion() async {
    if (_client == null) return (version: null, osId: null);

    final versionIdRegex = RegExp(
      r'^VERSION_ID="?([^"\n]+)"?$',
      multiLine: true,
    );
    final idRegex = RegExp(r'^ID="?([^"\n]+)"?$', multiLine: true);
    final semverRegex = RegExp(r'\bv?(\d+\.\d+(?:\.\d+)?)\b');

    final commands = <String>[
      'cat /etc/os-release 2>/dev/null',
      'cat /etc/librescoot-release 2>/dev/null',
      'cat /etc/issue 2>/dev/null',
    ];

    for (final command in commands) {
      try {
        debugPrint('SSH: checking firmware version via `$command`');
        final output = await runCommand(command);

        final idMatch = idRegex.firstMatch(output);
        final osId = idMatch?.group(1)?.trim();

        final versionIdMatch = versionIdRegex.firstMatch(output);
        if (versionIdMatch != null) {
          final version = _normalizeVersion(versionIdMatch.group(1)!);
          debugPrint('SSH: parsed VERSION_ID -> $version');
          return (version: version, osId: osId);
        }

        final semverMatch = semverRegex.firstMatch(output);
        if (semverMatch != null) {
          final version = _normalizeVersion(semverMatch.group(1)!);
          debugPrint('SSH: parsed semver -> $version');
          return (version: version, osId: osId);
        }

        debugPrint('SSH: no version match from command output');
      } catch (e) {
        debugPrint('SSH: command failed during version detection: $e');
        continue;
      }
    }

    return (version: null, osId: null);
  }

  String _normalizeVersion(String raw) {
    final trimmed = raw.trim();
    // Only add 'v' prefix for semver-like versions (e.g. 1.15.0), not channel tags
    if (trimmed.startsWith('v') || !RegExp(r'^\d').hasMatch(trimmed)) {
      return trimmed;
    }
    return 'v$trimmed';
  }

  String? _extractVersionFromText(String text) {
    final match = RegExp(r'\bv?(\d+\.\d+(?:\.\d+)?)\b').firstMatch(text);
    if (match == null) return null;
    return _normalizeVersion(match.group(1)!);
  }

  double _versionToNumber(String version) {
    final clean = version.trim().toLowerCase().replaceFirst('v', '');
    final parts = clean.split('.');
    final major = parts.isNotEmpty ? int.tryParse(parts[0]) ?? 0 : 0;
    final minor = parts.length > 1 ? int.tryParse(parts[1]) ?? 0 : 0;
    final patch = parts.length > 2 ? int.tryParse(parts[2]) ?? 0 : 0;
    return (major * 1000000) + (minor * 1000) + patch.toDouble();
  }

  String _resolveDeviceCredential(String version) {
    if (_deviceConfig == null || _deviceConfig!.isEmpty) {
      debugPrint(
        'SSH: no device profile available, using default configuration',
      );
      return '';
    }

    final normalized = _normalizeVersion(version);
    debugPrint('SSH: resolving device configuration for version "$version"');

    // Try exact match first
    if (_deviceConfig!.containsKey(normalized)) {
      return _deviceConfig![normalized]!;
    }
    if (_deviceConfig!.containsKey(version)) {
      return _deviceConfig![version]!;
    }
    final withoutV = normalized.replaceFirst('v', '');
    if (_deviceConfig!.containsKey(withoutV)) {
      return _deviceConfig![withoutV]!;
    }

    final parts = withoutV.split('.');
    if (parts.length == 3) {
      final majorMinor = 'v${parts[0]}.${parts[1]}';
      if (_deviceConfig!.containsKey(majorMinor)) {
        return _deviceConfig![majorMinor]!;
      }
    }

    // Try to find closest version
    final versionNum = _versionToNumber(normalized);
    String? closestVersion;
    double closestDiff = double.infinity;

    for (final key in _deviceConfig!.keys) {
      final keyNum = _versionToNumber(key);
      final diff = (keyNum - versionNum).abs();
      if (diff < closestDiff) {
        closestDiff = diff;
        closestVersion = key;
      }
    }

    if (closestVersion != null) {
      debugPrint('SSH: using closest profile entry "$closestVersion"');
      return _deviceConfig![closestVersion]!;
    }

    throw Exception('No device config found for version $version');
  }

  /// Rebuild a dropped client, or throw naming [operation].
  ///
  /// _lastPassword survives everything except an explicit disconnect(), so a
  /// client lost to an idle timeout or to invalidateConnection can be rebuilt
  /// without asking the user again.
  /// The live client, or a failure that says which operation lost it.
  ///
  /// The alternative is `_client!`, which reports a null-assertion with no
  /// indication of what was being attempted. Callers that can reconnect should
  /// go through [_ensureConnected] first; this is for the point of use.
  SSHClient _requireClient(String operation) {
    final client = _client;
    if (client == null) {
      throw Exception('SSH session lost during $operation');
    }
    return client;
  }

  /// Re-establish the session if it is gone, for a caller that wants the
  /// reconnect to happen at a point it can show rather than lazily inside the
  /// next upload.
  Future<void> ensureConnected(String operation) => _ensureConnected(operation);

  Future<void> _ensureConnected(String operation) async {
    if (_client != null) return;
    if (_lastPassword == null) {
      throw Exception(
        'SSH session lost before $operation, with no stored credential to '
        'resume it.',
      );
    }
    debugPrint('SSH: client gone, reconnecting for $operation');
    await _reconnect();
  }

  /// Run a command on the connected device.
  Future<String> runCommand(
    String command, {
    Duration timeout = const Duration(seconds: 60),
    bool replayOnDisconnect = false,
  }) async {
    await _ensureConnected('command');

    return executeWithReplayPolicy(
      execute: () => _runCommandOnce(command, timeout),
      reconnect: () async {
        debugPrint('SSH: replay-safe command disconnected, reconnecting once');
        await _reconnect();
      },
      invalidateConnection: () {
        _client?.close();
        _client = null;
      },
      isDisconnect: (error) =>
          _looksLikeDisconnect(error.toString().toLowerCase()),
      replayOnDisconnect: replayOnDisconnect && _lastPassword != null,
    );
  }

  Future<String> _runCommandOnce(String command, Duration timeout) async {
    final session = await _requireClient('command').execute(command);
    final stdout = StringBuffer();
    final stderr = StringBuffer();

    final stdoutDone = () async {
      await for (final data in session.stdout) {
        stdout.write(utf8.decode(data));
      }
    }();

    final stderrDone = () async {
      await for (final data in session.stderr) {
        stderr.write(utf8.decode(data));
      }
    }();

    try {
      await Future.wait([
        stdoutDone,
        stderrDone,
        session.done,
      ]).timeout(timeout);
    } catch (_) {
      // A timed-out session stays open otherwise, and every stalled command
      // costs another channel until the connection hits its limit and stops
      // accepting new ones.
      session.close();
      rethrow;
    }

    final exitCode = session.exitCode;
    if (exitCode != null && exitCode != 0) {
      throw Exception(
        'Command failed (exit $exitCode): $command'
        '${stderr.isNotEmpty ? '\nstderr: ${stderr.toString().trim()}' : ''}',
      );
    }

    return stdout.toString();
  }

  /// Run [command], handing stdout and stderr to the callbacks as the bytes
  /// arrive. Unlike [runCommand] this returns the exit code instead of
  /// throwing, because callers here want to distinguish mender's own failure
  /// from a transport failure and want its stderr verbatim.
  ///
  /// [timeout] has to cover a full artifact install, which writes several
  /// hundred megabytes to eMMC on a slow SoC.
  Future<({int exitCode, String stdout, String stderr})> runStreaming(
    String command, {
    void Function(String chunk)? onStdout,
    void Function(String chunk)? onStderr,
    Duration timeout = const Duration(minutes: 30),
  }) async {
    if (_client == null) {
      if (_lastPassword == null) throw Exception('Not connected');
      await _reconnect();
    }

    final session = await _requireClient('streaming command').execute(command);
    final stdout = StringBuffer();
    final stderr = StringBuffer();

    final stdoutDone = () async {
      await for (final data in session.stdout) {
        final chunk = utf8.decode(data, allowMalformed: true);
        stdout.write(chunk);
        onStdout?.call(chunk);
      }
    }();
    final stderrDone = () async {
      await for (final data in session.stderr) {
        final chunk = utf8.decode(data, allowMalformed: true);
        stderr.write(chunk);
        onStderr?.call(chunk);
      }
    }();

    // A timeout used to throw straight out of here, leaving the session open,
    // the remote command running and both drain futures pending. A retry then
    // started a second mender-update install against a board where the first
    // still held the lock. SIGTERM first so mender gets a chance to unwind,
    // then close the channel either way; killing the session ends both
    // streams, which is what lets the drains finish.
    try {
      await Future.wait([
        stdoutDone,
        stderrDone,
        session.done,
      ]).timeout(timeout);
    } catch (e) {
      try {
        session.kill(SSHSignal.TERM);
      } catch (killError) {
        debugPrint('SSH: could not signal the remote command: $killError');
      }
      session.close();
      // The drains are still listening on streams that are about to end.
      // Swallow whatever they finish with: the error being reported is [e],
      // and an unhandled one from here would take the isolate down instead.
      unawaited(stdoutDone.catchError((_) {}));
      unawaited(stderrDone.catchError((_) {}));
      rethrow;
    }

    return (
      exitCode: session.exitCode ?? -1,
      stdout: stdout.toString(),
      stderr: stderr.toString(),
    );
  }

  /// True when the board carries a usable mender client. The oldest images in
  /// the field may not, which is the one thing that makes an upgrade
  /// impossible on an otherwise healthy Librescoot board.
  Future<bool> hasMenderUpdate() async {
    try {
      final out = await runCommand(
        'command -v mender-update 2>/dev/null; true',
        replayOnDisconnect: true,
      );
      return out.trim().isNotEmpty;
    } catch (e) {
      debugPrint('SSH: mender-update probe failed: $e');
      return false;
    }
  }

  Future<int?> freeBytesOn(String path) async {
    try {
      return parseDfFreeBytes(
        await runCommand(
          'df -kP ${_shellEscape(path)}',
          replayOnDisconnect: true,
        ),
      );
    } catch (e) {
      debugPrint('SSH: df probe failed: $e');
      return null;
    }
  }

  /// Size in bytes of a remote file, or null when it does not exist or the
  /// probe could not be read. A preflight uses this to see whether an
  /// artifact is already sitting at its seed path from an earlier attempt,
  /// so a retry only has to account for the shortfall.
  Future<int?> remoteFileSizeBytes(String path) async {
    try {
      final out = await runCommand(
        'stat -c%s ${_shellEscape(path)} 2>/dev/null; true',
        replayOnDisconnect: true,
      );
      final trimmed = out.trim();
      return trimmed.isEmpty ? null : int.tryParse(trimmed);
    } catch (e) {
      debugPrint('SSH: file size probe failed for $path: $e');
      return null;
    }
  }

  Future<String?> menderArtifactName() async {
    try {
      final out = await runCommand(
        'mender-update show-artifact 2>/dev/null; true',
        replayOnDisconnect: true,
      );
      final name = out.trim();
      return name.isEmpty ? null : name;
    } catch (e) {
      debugPrint('SSH: show-artifact failed: $e');
      return null;
    }
  }

  Future<Map<String, String>> readOsRelease() async {
    try {
      return parseOsRelease(
        await runCommand(
          'cat /etc/os-release 2>/dev/null; true',
          replayOnDisconnect: true,
        ),
      );
    } catch (e) {
      debugPrint('SSH: os-release read failed: $e');
      return const {};
    }
  }

  /// Re-establish the SSH session using the credentials that worked on the
  /// last successful [_connect]. Skips the post-auth setup (pm-stop, sftp
  /// check, version detect) since that state is already known. Concurrent
  /// callers share the same in-flight attempt.
  Future<void> _reconnect() async {
    final existing = _reconnectInFlight;
    if (existing != null) {
      await existing;
      return;
    }
    final attempt = _doReconnect();
    _reconnectInFlight = attempt;
    try {
      await attempt;
    } finally {
      _reconnectInFlight = null;
    }
  }

  Future<void> _doReconnect() async {
    final pw = _lastPassword;
    if (pw == null) {
      throw Exception('No prior connection to recover');
    }
    debugPrint('SSH: silent reconnect to $_lastHost');
    final socket = await SSHSocket.connect(
      _lastHost,
      sshPort,
      timeout: connectionTimeout,
    );
    final client = SSHClient(
      keepAliveInterval: const Duration(seconds: 5),
      socket,
      username: sshUser,
      onPasswordRequest: () => pw,
    );
    try {
      await client.authenticated;
    } catch (e) {
      client.close();
      rethrow;
    }
    _client = client;
    debugPrint('SSH: silent reconnect succeeded');
  }

  /// Upload a file to the device via SFTP with progress reporting.
  /// Falls back to cat-over-stdin if SFTP is unavailable.
  Future<void> uploadFile(
    Uint8List content,
    String remotePath, {
    void Function(int bytesSent, int totalBytes)? onProgress,
  }) async {
    await _ensureConnected('file upload');

    // Scale timeout with file size: at least 60s, plus 1s per 100KB
    final timeoutSecs = 60 + (content.length / (100 * 1024)).ceil();
    final timeout = Duration(seconds: timeoutSecs);

    if (_sftpAvailable) {
      try {
        await _uploadViaSftp(content, remotePath, onProgress).timeout(timeout);
      } catch (e) {
        debugPrint('SSH: SFTP upload failed ($e), falling back to cat');
        _sftpAvailable = false;
        // The SFTP attempt can spend the whole timeout before failing, which
        // is long enough for the session to have gone with it. The fallback
        // needs a client of its own rather than the one checked on entry.
        await _ensureConnected('upload fallback');
        await _uploadViaCat(content, remotePath).timeout(timeout);
      }
    } else {
      await _uploadViaCat(content, remotePath).timeout(timeout);
    }

    // Make executable if needed
    if (remotePath.endsWith('.sh') || remotePath.contains('fw_setenv')) {
      await runCommand('chmod +x $remotePath');
    }
  }

  Future<void> _uploadViaSftp(
    Uint8List content,
    String remotePath,
    void Function(int bytesSent, int totalBytes)? onProgress,
  ) async {
    final sftp = await _requireClient('SFTP upload').sftp();
    try {
      final file = await sftp.open(
        remotePath,
        mode:
            SftpFileOpenMode.write |
            SftpFileOpenMode.create |
            SftpFileOpenMode.truncate,
      );
      try {
        const chunkSize = 64 * 1024;
        final stream = Stream<Uint8List>.fromIterable(
          Iterable.generate((content.length + chunkSize - 1) ~/ chunkSize, (i) {
            final start = i * chunkSize;
            final end = (start + chunkSize).clamp(0, content.length);
            return Uint8List.sublistView(content, start, end);
          }),
        );

        final writer = file.write(
          stream,
          onProgress: (total) => onProgress?.call(total, content.length),
        );
        await writer.done;
      } finally {
        await file.close();
      }
    } finally {
      sftp.close();
    }
  }

  Future<void> _uploadViaCat(Uint8List content, String remotePath) async {
    final session = await _requireClient('upload').execute('cat > $remotePath');
    session.stdin.add(content);
    await session.stdin.close();
    // Drain stdout/stderr to prevent blocking
    final stdoutDone = () async {
      await for (final _ in session.stdout) {}
    }();
    final stderrDone = () async {
      await for (final _ in session.stderr) {}
    }();
    await Future.wait([stdoutDone, stderrDone, session.done]);
  }

  /// Upload fw_setenv and configure bootloader for mass storage mode
  Future<void> configureMassStorageMode() async {
    // No guard: every step here goes through runCommand or uploadFile, both
    // of which reconnect a dropped client themselves.

    // Check if the device already has fw_setenv and fw_env.config (Librescoot).
    // If so, use the device's own tools and config (correct env offsets).
    // If not (stock scooterOS), upload our bundled versions.
    final hasNativeFwSetenv =
        (await runCommand(
          'command -v fw_setenv >/dev/null 2>&1 && echo yes || echo no',
        )).trim() ==
        'yes';
    final hasNativeConfig =
        (await runCommand(
          'test -f /etc/fw_env.config && echo yes || echo no',
        )).trim() ==
        'yes';

    final String fwSetenvCmd;
    final String configFlag;

    if (hasNativeFwSetenv && hasNativeConfig) {
      debugPrint('SSH: using device-native fw_setenv and /etc/fw_env.config');
      fwSetenvCmd = 'fw_setenv';
      configFlag = '';
    } else {
      debugPrint('SSH: uploading bundled fw_setenv and fw_env.config');
      final fwSetenv = await _readToolAsset('fw_setenv');
      final fwEnvConfig = await _readToolAsset('fw_env.config');
      debugPrint('SSH: uploading fw_setenv (${fwSetenv.length} bytes)...');
      await uploadFile(fwSetenv, '/tmp/fw_setenv');
      debugPrint(
        'SSH: uploading fw_env.config (${fwEnvConfig.length} bytes)...',
      );
      await uploadFile(fwEnvConfig, '/tmp/fw_env.config');
      debugPrint('SSH: uploads complete');
      fwSetenvCmd = '/tmp/fw_setenv';
      configFlag = '-c /tmp/fw_env.config';
    }

    // Set bootloader variables for USB mass storage mode.
    // Some boards need fuse programming in bootcmd (legacy).
    // If that fails, fall back to plain UMS bootcmd.
    // Use single quotes so the remote shell passes semicolons through
    // to fw_setenv as a single value argument.
    //
    // This bootcmd stays until an image is written, and putting it back early
    // is not a courtesy but a hazard. UMS is the only state on this board
    // reachable without a working Linux: entering it needs fw_setenv, which
    // needs a booted rootfs. So a board parked here can always be flashed,
    // and a board taken out of here that then fails to boot cannot be brought
    // back without opening it up.
    //
    // Restoring the old bootcmd would also require knowing nothing has been
    // written yet, which is not knowable: another instance may have started a
    // write, and a partly written rootfs leaves an environment nobody should
    // trust. Once anything has been written the only guaranteed-correct state
    // is a complete image.
    //
    // A run abandoned at the flash screen therefore leaves the board in UMS on
    // purpose. Relaunching picks it straight back up, which is what
    // mdbDetectedUmsSkipping is for.
    final fullBootcmd =
        "$fwSetenvCmd $configFlag bootcmd 'fuse prog -y 0 5 0x00002860; "
        "fuse prog -y 0 6 0x00000010; ums 0 mmc 1'";
    final fallbackBootcmd = "$fwSetenvCmd $configFlag bootcmd 'ums 0 mmc 1'";

    try {
      debugPrint('SSH: running: $fullBootcmd');
      final result = await runCommand(fullBootcmd);
      debugPrint('SSH: fw_setenv bootcmd result: "$result"');
    } catch (e) {
      debugPrint('SSH: full bootcmd failed ($e), trying fallback...');
      final result = await runCommand(fallbackBootcmd);
      debugPrint('SSH: fallback fw_setenv result: "$result"');
    }

    // Give fw_setenv time to flush to eMMC
    await Future.delayed(const Duration(seconds: 2));

    final delayResult = await runCommand(
      '$fwSetenvCmd $configFlag bootdelay 0',
    );
    debugPrint('SSH: fw_setenv bootdelay result: "$delayResult"');

    // Give fw_setenv time to flush
    await Future.delayed(const Duration(seconds: 2));
    debugPrint('SSH: bootloader configured for mass storage mode');
  }

  /// Where settings-service persists whether its service overlay is active.
  ///
  /// Writing another service's state file is a coupling, and it is the one
  /// that works. The file is the only part of service mode that outlives a
  /// reboot, and the board doing the arming is frequently not running
  /// settings-service at all: on a clean install it is stage 0, which has
  /// redis but no settings-service to take an `apply:service` command.
  static const String serviceModeStatePath = '/data/service-mode.json';

  /// Everything the installer stages lives under this one directory.
  static const String installerDir = '/data/installer';

  /// What a finished run leaves behind, one directory per run: the record, and
  /// the logs from both halves of it.
  ///
  /// Under [installerDir] like everything else, which is what makes the sweep
  /// at the end of a run selective rather than an rm -rf. That is a footgun in
  /// exchange for one place to look, so there is exactly one definition of what
  /// a sweep keeps: [installerSweepCommand].
  static const String installerHistoryDir = '$installerDir/history';

  /// The last run's record, and the current run's progress. Pointers into
  /// [installerHistoryDir] rather than the record itself.
  static const String installerLastInstall = '$installerDir/last-install';
  static const String installerRunState = '$installerDir/run-state';

  /// Where those three lived before everything moved under one directory. Read
  /// as a fallback so an installer meeting a board an older one touched can
  /// still tell what happened to it; never written.
  static const String legacyHistoryDir = '/data/installer-runs';
  static const String legacyLastInstall = '/data/last-install';
  static const String legacyRunState = '/data/installer-run-state';

  /// Clear the staging a run leaves behind without taking the record with it.
  ///
  /// One definition because there are three callers: the laptop's cleanup, the
  /// trampoline's own, and the finalize. An rm -rf in any of them would delete
  /// the history the other two are careful to keep.
  static const String installerSweepCommand =
      'find $installerDir -mindepth 1 -maxdepth 1 '
      '! -name history ! -name scripts ! -name onboot.sh.bak '
      '! -name last-install ! -name run-state '
      '-exec rm -rf {} + 2>/dev/null || true';

  /// The scripts the board runs on its own: the trampoline's two halves, the
  /// cleanup, and a rescue payload when an emergency reboot leaves one.
  static const String installerScriptsDir = '$installerDir/scripts';

  /// The path librescoot-onboot.service watches, and the only installer file
  /// outside [installerDir]. Fixed by the unit
  /// (`ConditionPathExists=/data/onboot.sh`, `ExecStart=/data/onboot.sh`), so
  /// it cannot move.
  static const String onbootPath = '/data/onboot.sh';

  /// Where a user's own onboot.sh goes while ours holds the path.
  static const String displacedOnbootPath = '$installerDir/onboot.sh.bak';

  /// The coordinator. It runs the numbered install phases it finds in
  /// [installerScriptsDir], in order, and takes itself out once none are
  /// left.
  ///
  /// One writer on purpose. The trampoline used to assemble its own
  /// post-reboot half straight into /data/onboot.sh, which made the boot path
  /// something two producers wrote to at different times. The installer
  /// installs this once, up front, and everything else only drops files into
  /// the scripts directory. What runs at boot is then a question about the
  /// contents of one directory rather than about which producer wrote last.
  ///
  /// Deliberately small and deliberately dumb. It sequences, counts attempts
  /// and retires. It knows no phase by name, which is what lets a phase
  /// abandon the run by deleting the phases after it and dropping in a
  /// lower-numbered one; there is no abort case here to get wrong.
  ///
  /// Only `NN-name.sh` is run at boot. The first phase is launched by the
  /// laptop, over the link, and carries a DBC flash: it is deliberately not
  /// numbered, so a board that died in the middle of it comes back without
  /// re-flashing a dashboard unattended.
  @visibleForTesting
  static const String onbootShim = r"""#!/bin/sh
# Installed by the Librescoot installer. Runs the numbered install phases left
# in /data/installer/scripts and removes itself once none are left.
SCRIPTS=/data/installer/scripts

# Counts the attempt before making it. A phase that wedges the boot never
# reaches its own end, so counting afterwards counts the runs that already
# worked and retries the ones that did not, forever.
run_one() {
  tries="$1.tries"
  n=$(cat "$tries" 2>/dev/null || echo 0)
  n=$((n + 1))
  echo "$n" > "$tries"
  if [ "$n" -gt 3 ]; then
    rm -f "$1" "$tries"
    return 0
  fi
  sh "$1"
}

for phase in "$SCRIPTS"/[0-9][0-9]-*.sh; do
  # Re-checked inside the loop, not just at the top: the glob was expanded
  # before the first phase ran, and a phase that abandons the run deletes the
  # ones after it.
  [ -f "$phase" ] || continue
  run_one "$phase"
done

# Each phase removes itself when it is done, so no phases left is the signal
# that there is nothing to coordinate any more.
for phase in "$SCRIPTS"/[0-9][0-9]-*.sh; do
  [ -f "$phase" ] && exit 0
done
if [ -f /data/installer/onboot.sh.bak ]; then
  mv -f /data/installer/onboot.sh.bak /data/onboot.sh
else
  rm -f /data/onboot.sh
fi
""";

  /// Take the coordinator out and give a displaced onboot.sh back.
  ///
  /// The coordinator retires itself when it runs out of phases, which covers
  /// every run that reaches a boot with none left. It does not cover a run
  /// that installed it and then never queued a phase, and the sweep at the end
  /// of a run deletes the directory the displaced script is saved in. So the
  /// finish asks explicitly rather than relying on a boot to notice.
  ///
  /// Refuses while a phase is still queued: that phase is going to run, and it
  /// needs the coordinator to be there when it does.
  Future<void> retireOnbootCoordinator() async {
    try {
      await runCommand(onbootRetireCommand);
      debugPrint('SSH: retired the onboot coordinator');
    } catch (e) {
      debugPrint('SSH: could not retire the onboot coordinator (ok): $e');
    }
  }

  /// Keep the last few runs and no more.
  ///
  /// The logs are small against the hundreds of megabytes a run stages, which
  /// is why they are kept at all, but a scooter that is installed onto
  /// repeatedly would otherwise accumulate them forever. Newest first, so what
  /// survives is what somebody is most likely to be asked about.
  static const int historyRunsKept = 5;

  /// Trim [installerHistoryDir] to the newest [historyRunsKept] runs.
  Future<void> trimInstallHistory() async {
    try {
      await runCommand(
        'cd $installerHistoryDir 2>/dev/null && '
        'ls -1t 2>/dev/null | tail -n +${historyRunsKept + 1} | '
        'while read -r old; do rm -rf -- "\$old"; done; true',
      );
    } catch (e) {
      debugPrint('SSH: could not trim the install history (ok): \$e');
    }
  }

  /// Put the laptop's own log beside the board's, so the two halves of a run
  /// can be read together.
  ///
  /// A snapshot: the file is still being written to, and the lines after this
  /// are the handover, which the phase logs on the board anyway. Best effort,
  /// and last, because a run that cannot copy a log has still installed.
  Future<void> keepInstallerLog({
    required String runId,
    required String localPath,
  }) async {
    try {
      final bytes = await File(localPath).readAsBytes();
      await runCommand('mkdir -p $installerHistoryDir/\$runId');
      await uploadFile(bytes, '$installerHistoryDir/\$runId/installer.log');
      debugPrint('SSH: kept the installer log for \$runId on the board');
    } catch (e) {
      debugPrint('SSH: could not keep the installer log (ok): \$e');
    }
  }

  @visibleForTesting
  static const String onbootRetireCommand = r"""
for phase in /data/installer/scripts/[0-9][0-9]-*.sh; do
  [ -e "$phase" ] || continue
  exit 0
done
if [ -f /data/onboot.sh ] && grep -Fq 'Installed by the Librescoot installer' /data/onboot.sh; then
  if [ -f /data/installer/onboot.sh.bak ]; then
    mv -f /data/installer/onboot.sh.bak /data/onboot.sh
  else
    rm -f /data/onboot.sh
  fi
fi
""";

  /// Put the coordinator in place, saving a user's own onboot.sh if one is
  /// there.
  ///
  /// Two markers are checked, not one. Our own shim is the obvious case. The
  /// other is a board an installer from before the coordinator touched: those
  /// wrote their post-reboot half straight to this path, and saving one as if
  /// it were the user's script means handing it back on retirement, which
  /// re-arms a dead run against a staging directory that has since been swept.
  Future<void> installOnbootShim() async {
    await runCommand(onbootInstallCommand);
    debugPrint('SSH: installed the onboot coordinator');
  }

  @visibleForTesting
  static const String onbootInstallCommand =
      'mkdir -p $installerScriptsDir; '
      'if [ -f $onbootPath ] && '
      "   ! grep -Fq 'Installed by the Librescoot installer' $onbootPath && "
      "   ! grep -Fq 'Auto-generated by installer trampoline' $onbootPath; then "
      '  cp -f $onbootPath $displacedOnbootPath; '
      'fi; '
      "cat > $onbootPath.new << 'LSIONBOOT'\n"
      '$onbootShim'
      'LSIONBOOT\n'
      'chmod +x $onbootPath.new; mv -f $onbootPath.new $onbootPath; sync';

  /// Arm settings-service's service overlay for the reboot into the freshly
  /// installed image.
  ///
  /// The image that boots next has vehicle-service, which the stage-0 image
  /// did not. Its usb0 gate closes once enough keycards are paired, and by
  /// this point in a run they are, so the board withdraws the installer's
  /// only route in at the moment it has to check that the install took.
  /// `scooter.usb0-policy = always-on` short-circuits that gate open, and the
  /// setting is transient: it cannot be written before the reboot, and
  /// writing it after one needs the link it is there to keep.
  ///
  /// settings-service re-applies the overlay from this file on its next
  /// start, after loading the base settings and before it signals readiness,
  /// and its unit is ordered `Before=librescoot-vehicle.service`. So the
  /// policy is already in the settings hash the first time vehicle-service
  /// reads it. That ordering is the whole reason for preferring this to a
  /// boot script: a script races the settings load and has to poll for it,
  /// and one that guessed wrong wrote a policy that was overwritten a second
  /// later.
  ///
  /// The overlay parks auto-standby, the hibernation timer and the alarm
  /// alongside the policy, which is what the installer wants for the length
  /// of a run anyway. It also forces `scooter.handlebar-unlocked`, which the
  /// install does not care about either way.
  ///
  /// A board that rolls back is on stage 0 again with no settings-service to
  /// read this, and equally no vehicle-service to take usb0 down, so there is
  /// nothing for it to lose.
  ///
  /// Best effort: a board this could not be written to still gets its reboot,
  /// and the reconnect afterwards is what reports whether it came back.
  Future<void> armServiceMode() async {
    try {
      await runCommand(serviceModeArmCommand);
      debugPrint('SSH: armed service mode for the reboot');
    } catch (e) {
      debugPrint('SSH: could not arm service mode (ok): $e');
    }
  }

  /// Through a temporary file, so a board that loses power mid-write cannot
  /// leave half a JSON object behind. settings-service reads an unparseable
  /// file as inactive, which is the safe direction to fail in, but losing the
  /// link is the failure this exists to prevent.
  @visibleForTesting
  static const String serviceModeArmCommand = r"""
tmp=/data/.service-mode.json.installer
printf '%s\n' '{"active":true,"name":"service"}' > "$tmp"
sync
mv -f "$tmp" /data/service-mode.json
sync
""";

  /// The settings field settings-service publishes while its overlay is
  /// active.
  ///
  /// It carries a schema default, so a build that has service mode always has
  /// this field in the settings hash and a build without it never does. That
  /// makes one read serve as both the capability probe and the confirmation.
  ///
  /// It also answers a second question worth asking before capturing
  /// anything: the field only appears once settings-service has stamped the
  /// hash from the schema and the user's TOML together. Applying the overlay
  /// before that would capture schema defaults as the base and restore those
  /// at the end, over whatever the owner had actually configured.
  static const String serviceModeStatusField = 'dashboard.service-mode-active';

  /// Turn service mode on for the rest of the run, and report whether it took.
  ///
  /// Armed at connect rather than only before the reboot, because the overlay
  /// does more than hold usb0 up. It parks auto-standby, the hibernation timer
  /// and the alarm for exactly as long as the run lasts, captures what those
  /// were first, keeps its own values out of `/data/settings.toml` entirely,
  /// and puts the captured values back on clear. That is the same job the
  /// installer was doing by hand with `lsc set`, a copy of settings.toml and a
  /// settings-service restart at the end, done by the service that owns the
  /// settings.
  ///
  /// A false return is not a failure. Stage 0 and stock boards have no
  /// settings-service at all, and anything built before 2026-06-22 has one
  /// without the overlay, so the caller keeps the manual path for those.
  ///
  /// Already-on counts as on. A board that arrives in service mode captured
  /// its base when it was turned on, and that base is the one worth restoring.
  Future<bool> enableServiceMode() async {
    try {
      final answer = (await runCommand(serviceModeEnableCommand)).trim();
      switch (answer) {
        case 'on':
          debugPrint('SSH: service mode is live');
          return true;
        case 'already-on':
          debugPrint('SSH: service mode was already live, leaving it');
          return true;
        case 'unsupported':
          debugPrint('SSH: no service mode on this board, using the manual path');
          return false;
        default:
          debugPrint('SSH: service mode did not come up ($answer)');
          return false;
      }
    } catch (e) {
      debugPrint('SSH: could not ask about service mode (ok): $e');
      return false;
    }
  }

  /// One round trip: probe, apply, confirm.
  ///
  /// The apply is consumed off a list, so the confirmation has to be a read of
  /// the published status rather than the push succeeding. Ten seconds is a
  /// long time for a BRPop that is already blocked on the list, and it is only
  /// ever spent on a board that answered the probe, so it cannot become a
  /// stall on the boards that have no overlay.
  @visibleForTesting
  static const String serviceModeEnableCommand = r"""
status=$(redis-cli -h localhost --raw hget settings dashboard.service-mode-active 2>/dev/null)
if [ -z "$status" ]; then echo unsupported; exit 0; fi
if [ "$status" = true ]; then echo already-on; exit 0; fi
redis-cli -h localhost lpush settings:overlay apply:service >/dev/null 2>&1
i=0
while [ $i -lt 10 ]; do
  sleep 1
  now=$(redis-cli -h localhost --raw hget settings dashboard.service-mode-active 2>/dev/null)
  if [ "$now" = true ]; then echo on; exit 0; fi
  i=$((i+1))
done
echo timeout
""";

  /// Hand the vehicle back: end service mode, let usb0 follow the dashboard
  /// again, and unlock.
  ///
  /// Detached, because it severs the transport it runs over. Restoring the
  /// policy makes vehicle-service tear down the USB gadget synchronously, so
  /// a command that is not detached dies there and takes the unlock with it.
  Future<void> runFinalizePhase() async {
    await runCommand(
      'nohup sh $installerScriptsDir/90-finalize.sh '
      '>/dev/null 2>&1 </dev/null &',
    );
  }


  /// Reboot the device
  Future<void> reboot() async {
    // No guard: every command here goes through runCommand, which reconnects
    // a dropped client itself.
    final rebootCommands = <String>[
      'reboot',
      '/sbin/reboot',
      'busybox reboot',
      'shutdown -r now',
    ];

    var requested = false;
    final misses = <String>[];
    for (final cmd in rebootCommands) {
      try {
        debugPrint('SSH: sending reboot command: $cmd');
        await runCommand(cmd, replayOnDisconnect: false);
        debugPrint('SSH: reboot command accepted: $cmd');
        requested = true;
        break;
      } catch (e) {
        final error = e.toString().toLowerCase();
        if (_looksLikeDisconnect(error)) {
          debugPrint('SSH: reboot likely triggered (connection dropped): $cmd');
          requested = true;
          break;
        }
        // Each entry covers a different image, so most runs miss the first
        // few. Only an exhausted list is a failure, and saying so per rung
        // sends whoever reads the log after a real fault to the wrong place.
        misses.add('$cmd -> $e');
        debugPrint('SSH: reboot command not available: $cmd');
      }
    }

    if (!requested) {
      throw Exception(
        'Failed to trigger reboot with known commands: ${misses.join('; ')}',
      );
    }

    debugPrint('SSH: disconnecting local SSH client after reboot attempt');
    disconnect();
  }

  bool _looksLikeDisconnect(String error) {
    return error.contains('connection reset') ||
        error.contains('broken pipe') ||
        error.contains('socket') ||
        error.contains('eof') ||
        error.contains('closed');
  }

  Future<Uint8List> _readToolAsset(String fileName) async {
    final bundleCandidates = <String>[
      'assets/tools/$fileName',
      'assets/binaries/$fileName',
    ];
    for (final candidate in bundleCandidates) {
      try {
        final data = await rootBundle.load(candidate);
        debugPrint('SSH: loaded tool asset from bundle: $candidate');
        return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      } catch (_) {
        // Try next candidate
      }
    }

    final candidates = <String>[
      path.join(Directory.current.path, 'assets', 'tools', fileName),
      path.join(Directory.current.path, 'assets', 'binaries', fileName),
      path.join(
        Platform.resolvedExecutable,
        '..',
        'data',
        'flutter_assets',
        'assets',
        'tools',
        fileName,
      ),
      path.join(
        Platform.resolvedExecutable,
        '..',
        'data',
        'flutter_assets',
        'assets',
        'binaries',
        fileName,
      ),
    ];

    for (final candidate in candidates) {
      final file = File(candidate);
      if (await file.exists()) {
        return file.readAsBytes();
      }
    }

    throw Exception('Required tool asset not found: $fileName');
  }

  String? _parseSerial(String raw) {
    final matches = RegExp(
      r'0x[0-9a-fA-F]+',
    ).allMatches(raw).map((m) => m.group(0)!).toList();
    if (matches.isNotEmpty) {
      return matches
          .map(
            (part) =>
                part.replaceFirst(RegExp(r'^0x', caseSensitive: false), ''),
          )
          .join()
          .toLowerCase();
    }
    // soc0/serial_number is a bare 16-digit uppercase hex word, no 0x prefix.
    final bare = RegExp(r'^[0-9a-fA-F]{16}$').firstMatch(raw.trim());
    return bare?.group(0)!.toLowerCase();
  }

  /// Disconnect from device. Clears the cached auth so any subsequent
  /// [runCommand] will fail loudly instead of silently re-establishing —
  /// the reboot path relies on this so we don't auto-reconnect to a device
  /// that's mid-reboot.
  void disconnect() {
    _client?.close();
    _client = null;
    _lastPassword = null;
  }

  bool get isConnected => _client != null;

  /// Run a Redis HGET command on the MDB and return the value.
  Future<String?> redisHget(String hash, String field) async {
    try {
      final result = await runCommand(
        'redis-cli HGET $hash $field',
        replayOnDisconnect: true,
      );
      final value = result.trim();
      if (value.isEmpty || value == '(nil)') return null;
      return value;
    } catch (_) {
      return null;
    }
  }

  /// Run a Redis LPUSH command on the MDB.
  Future<void> redisLpush(
    String key,
    String value, {
    Duration timeout = const Duration(seconds: 60),
  }) async {
    final operationId =
        '${DateTime.now().microsecondsSinceEpoch}-${_redisQueueSequence++}';
    final command = buildDeduplicatedRedisLpushCommand(
      key: key,
      value: value,
      operationId: operationId,
    );
    await runCommand(command, timeout: timeout, replayOnDisconnect: true);
  }

  @visibleForTesting
  static String buildDeduplicatedRedisLpushCommand({
    required String key,
    required String value,
    required String operationId,
  }) {
    const script =
        "local fresh=redis.call('SET',KEYS[2],'1','EX',ARGV[2],'NX');"
        "if fresh then return redis.call('LPUSH',KEYS[1],ARGV[1]) end;"
        'return 0';
    final dedupKey = 'librescoot-installer:queue-op:$operationId';
    return 'redis-cli EVAL ${_shellEscape(script)} 2 '
        '${_shellEscape(key)} ${_shellEscape(dedupKey)} '
        '${_shellEscape(value)} 600';
  }

  /// Subscribe to a Redis pub/sub [channel] over a long-running SSH session.
  /// Yields one event per published message (the payload only). Caller must
  /// invoke [stop] on the returned subscription to terminate the session and
  /// release the SSH channel.
  ///
  /// SSH execute sessions never have a TTY, so redis-cli emits three plain
  /// lines per message: `message`, `<channel>`, `<payload>`. The bracketed
  /// `1) "message"` form only appears in interactive/TTY mode; the awk
  /// filter accepts both for safety. fflush() defeats line buffering so
  /// events arrive promptly.
  Future<({Stream<String> events, Future<void> Function() stop})>
  subscribeRedisChannel(String channel) async {
    await _ensureConnected('redis subscription');
    final escapedChannel = _shellEscape(channel);
    final cmd =
        'redis-cli SUBSCRIBE $escapedChannel 2>&1 | '
        "awk '"
        '/^(message|[0-9]+\\) "message")\$/ { state=1; next } '
        'state==1 { state=2; next } '
        'state==2 { sub(/^[0-9]+\\) "/, ""); sub(/"\$/, ""); print; fflush(); state=0; next }'
        "'";
    final session = await _requireClient('redis subscribe').execute(cmd);
    final controller = StreamController<String>();
    final decoder = const Utf8Decoder(allowMalformed: true);
    var buf = '';

    final stdoutSub = session.stdout.listen(
      (data) {
        buf += decoder.convert(data);
        var idx = buf.indexOf('\n');
        while (idx != -1) {
          final line = buf.substring(0, idx).trim();
          buf = buf.substring(idx + 1);
          if (line.isNotEmpty && !controller.isClosed) {
            controller.add(line);
          }
          idx = buf.indexOf('\n');
        }
      },
      onError: (Object e, StackTrace s) {
        if (!controller.isClosed) controller.addError(e, s);
      },
      onDone: () {
        final tail = buf.trim();
        if (tail.isNotEmpty && !controller.isClosed) controller.add(tail);
        if (!controller.isClosed) controller.close();
      },
    );
    // Drain stderr so the channel doesn't block on flow control.
    final stderrSub = session.stderr.listen((_) {});

    Future<void> stop() async {
      try {
        session.close();
      } catch (_) {}
      try {
        await stdoutSub.cancel();
      } catch (_) {}
      try {
        await stderrSub.cancel();
      } catch (_) {}
      if (!controller.isClosed) {
        await controller.close();
      }
    }

    return (events: controller.stream, stop: stop);
  }

  /// Run a Redis HGETALL on the MDB and return all field/value pairs.
  /// Returns an empty map on error or if the hash is empty.
  Future<Map<String, String>> redisHgetall(String hash) async {
    try {
      final result = await runCommand(
        'redis-cli HGETALL $hash',
        replayOnDisconnect: true,
      );
      final lines = result.split('\n');
      final out = <String, String>{};
      for (var i = 0; i + 1 < lines.length; i += 2) {
        final k = lines[i].trim();
        final v = lines[i + 1].trim();
        if (k.isEmpty) continue;
        out[k] = v;
      }
      return out;
    } catch (_) {
      return const <String, String>{};
    }
  }

  /// Snapshot battery / CBB / aux state to the installer log.
  /// One line per source so the log stays greppable. [tag] identifies
  /// the call site (e.g. 'health-check', 'pre-flash').
  Future<void> logScooterStats(String tag) async {
    final results = await Future.wait([
      redisHgetall('aux-battery'),
      redisHgetall('cb-battery'),
      redisHgetall('battery:0'),
      redisHgetall('battery:1'),
    ]);
    final aux = results[0];
    final cbb = results[1];
    final b0 = results[2];
    final b1 = results[3];

    String fmtAux() {
      if (aux.isEmpty) return 'no-data';
      final v = aux['voltage'];
      final c = aux['charge'];
      final s = aux['charge-status'];
      final parts = <String>[];
      if (v != null) parts.add('V=${v}mV');
      if (c != null) parts.add('charge=$c%');
      if (s != null && s.isNotEmpty) parts.add('status=$s');
      return parts.isEmpty ? 'no-data' : parts.join(' ');
    }

    String fmtCbb() {
      if (cbb.isEmpty) return 'no-data';
      final present = cbb['present'] == 'true';
      if (!present) return 'present=false';
      final parts = <String>['present=true'];
      if (cbb['charge'] != null) parts.add('charge=${cbb['charge']}%');
      if (cbb['state-of-health'] != null) {
        parts.add('soh=${cbb['state-of-health']}%');
      }
      if (cbb['cycle-count'] != null) parts.add('cycles=${cbb['cycle-count']}');
      if (cbb['temperature'] != null) parts.add('temp=${cbb['temperature']}C');
      if (cbb['cell-voltage'] != null) parts.add('V=${cbb['cell-voltage']}uV');
      if (cbb['current'] != null) parts.add('I=${cbb['current']}uA');
      if (cbb['charge-status'] != null && cbb['charge-status']!.isNotEmpty) {
        parts.add('status=${cbb['charge-status']}');
      }
      return parts.join(' ');
    }

    String fmtMain(Map<String, String> b) {
      if (b.isEmpty) return 'no-data';
      final present = b['present'] == 'true';
      if (!present) return 'present=false';
      final parts = <String>['present=true'];
      if (b['state'] != null) parts.add('state=${b['state']}');
      if (b['charge'] != null) parts.add('charge=${b['charge']}%');
      if (b['voltage'] != null) parts.add('V=${b['voltage']}mV');
      if (b['current'] != null) parts.add('I=${b['current']}mA');
      // Pick the hottest cell to keep the line short.
      final temps = <int>[];
      for (var i = 0; i < 4; i++) {
        final t = int.tryParse(b['temperature:$i'] ?? '');
        if (t != null) temps.add(t);
      }
      if (temps.isNotEmpty) {
        parts.add('temp=${temps.reduce((a, b) => a > b ? a : b)}C');
      }
      if (b['temperature-state'] != null) {
        parts.add('temp-state=${b['temperature-state']}');
      }
      if (b['state-of-health'] != null) {
        parts.add('soh=${b['state-of-health']}%');
      }
      if (b['cycle-count'] != null) parts.add('cycles=${b['cycle-count']}');
      if (b['serial-number'] != null && b['serial-number']!.isNotEmpty) {
        parts.add('sn=${b['serial-number']}');
      }
      return parts.join(' ');
    }

    debugPrint('Stats[$tag] aux: ${fmtAux()}');
    debugPrint('Stats[$tag] cbb: ${fmtCbb()}');
    debugPrint('Stats[$tag] battery:0: ${fmtMain(b0)}');
    debugPrint('Stats[$tag] battery:1: ${fmtMain(b1)}');
  }

  /// Get the current vehicle state from Redis.
  Future<String?> getVehicleState() async {
    return redisHget('vehicle', 'state');
  }

  /// Write `vehicle[state]` and publish it, without going through
  /// vehicle-service's own transitions.
  ///
  /// bluetooth-service watches this hash and forwards the value to the nRF52,
  /// which derives its BLE advertising mode from it: `parked` permits pairing
  /// with a device it already holds a bond for, `stand-by` does not. Setting
  /// it here opens that gate for the length of the pairing window without
  /// releasing the handlebar lock or arming the motor. vehicle-service owns
  /// the key and overwrites it on its next real transition, so every caller
  /// puts the previous value back when it is done.
  /// Disarm a trampoline left over from a run that did not finish.
  ///
  /// The trampoline installs /data/onboot.sh and lets the boot path re-run it
  /// up to three times, so an abandoned run stays armed: the next MDB reboot
  /// executes the old script against the old staging directory. This is the
  /// same retirement the trampoline performs on its own completion, including
  /// putting back a pre-existing onboot.sh if one was displaced.
  Future<void> disarmTrampolineOnboot() async {
    await runCommand(interruptedInstallDisarmCommand);
  }

  /// Undo the masking the trampoline applies, and start what it stopped.
  ///
  /// A run that died between masking and its own cleanup leaves these masked,
  /// which makes the vehicle unable to read a keycard or answer Bluetooth.
  /// keycard is started too: by this point a master card exists, or the
  /// installer's own keycard phase will handle teaching one in.
  Future<void> reviveInstallerServices() async {
    await runCommand(interruptedInstallServiceRecoveryCommand);
  }

  Future<void> forceVehicleState(String state) async {
    await runCommand(
      'redis-cli hset vehicle state $state >/dev/null; '
      'redis-cli publish vehicle state >/dev/null; true',
    );
  }

  /// Probe whether the connected MDB is running a full image with the redis
  /// stack. A minimal/bootstrap rootfs (e.g. flashed by mistake) answers SSH
  /// but ships no redis-cli, so every redis-backed step (the parked-state
  /// gate, the pre-flash lock, the health telemetry) fails with
  /// `redis-cli: not found`. Returns false when redis-cli is absent so the
  /// caller can route straight to re-flash instead of getting wedged.
  /// Which vehicle stack the board is running.
  ///
  /// Null means the board could not answer, which is not the same as
  /// [ServiceStack.none]. It used to be: one `systemctl` that timed out over a
  /// busy link seconds after a reboot was enough to report a finished install
  /// as a rollback to the bootstrap image, with the artifact name and
  /// os-release both saying otherwise. A board that is up but slow gets a few
  /// tries before this gives up on it.
  Future<ServiceStack?> detectServiceStack({int attempts = 12}) async {
    // os-release names the distribution outright, cannot be raced, and is
    // already read on this path. It only settles the stock case: the bootstrap
    // image carries the Librescoot ID too, so a librescoot ID still has to be
    // asked whether the stack is actually there.
    try {
      final id = (await readOsRelease())['ID'] ?? '';
      if (id.isNotEmpty && !id.startsWith('librescoot')) {
        debugPrint('SSH: stack from os-release ID "$id" -> stock');
        return ServiceStack.stock;
      }
    } catch (e) {
      debugPrint('SSH: os-release unreadable, falling back to units: $e');
    }

    for (var attempt = 1; attempt <= attempts; attempt++) {
      try {
        // redis-cli alone separates nothing: the bootstrap image ships valkey
        // so bluetooth-service can run during pairing, and stock ships its own
        // redis with its own schema. The vehicle unit is what every
        // redis-backed step here depends on, and it carries a different name
        // under each stack. Asking for both names is what keeps a healthy
        // stock board distinct from a board with no stack at all.
        final out = await runCommand(stackProbeScript);
        final answer = parseStackProbe(out);
        if (answer != null) {
          // Logged on the way out, not only when it goes wrong. This decides
          // whether a finished install is reported as a failure, and a
          // decision that leaves no trace in the log we ask users for cannot
          // be diagnosed from a report.
          debugPrint('SSH: stack probe -> ${answer.name} (attempt $attempt)');
          return answer;
        }
        debugPrint('SSH: stack probe gave nothing useful: ${out.trim()}');
      } catch (e) {
        debugPrint('SSH: stack probe failed (attempt $attempt): $e');
      }
      if (attempt < attempts) {
        await Future.delayed(const Duration(seconds: 5));
      }
    }
    debugPrint('SSH: stack probe never answered after $attempts attempts');
    return null;
  }

  /// systemd answers list-unit-files with nothing at all for the first minute
  /// or so of a boot, and an empty list looks exactly like a list with no
  /// vehicle unit in it. Emitting `unknown` for that keeps a board that has not
  /// finished starting from being reported as a board with no stack.
  ///
  /// The vehicle unit is `librescoot-vehicle` or `unu-vehicle`.
  /// `vehicle-service` is the binary Librescoot's unit runs, never a unit.
  @visibleForTesting
  static const stackProbeScript =
      r'''command -v redis-cli >/dev/null 2>&1 || { echo none; exit 0; }; '''
      r'''u=$(systemctl list-unit-files 2>/dev/null); '''
      r'''[ -z "$u" ] && { echo unknown; exit 0; }; '''
      r'''echo "$u" | grep -q "^librescoot-vehicle" && { echo librescoot; exit 0; }; '''
      r'''echo "$u" | grep -q "^unu-vehicle" && { echo stock; exit 0; }; '''
      r'''echo none''';

  /// The probe answers with one word. Anything else is not an answer.
  @visibleForTesting
  static ServiceStack? parseStackProbe(String output) {
    final lines = output
        .split('\n')
        .map((l) => l.trim())
        .where((l) => l.isNotEmpty)
        .toList();
    if (lines.isEmpty) return null;
    return switch (lines.last) {
      'librescoot' => ServiceStack.librescoot,
      'stock' => ServiceStack.stock,
      'none' => ServiceStack.none,
      // `unknown` is the board saying it could not answer, which is the same
      // as not answering: null, so the caller retries rather than concluding.
      _ => null,
    };
  }

  /// Wait for a specific vehicle state, polling every [interval].
  /// Returns true if the state was reached, false on timeout.
  Future<bool> waitForVehicleState(
    String targetState, {
    Duration timeout = const Duration(seconds: 120),
    Duration interval = const Duration(seconds: 2),
  }) async {
    final deadline = DateTime.now().add(timeout);
    while (DateTime.now().isBefore(deadline)) {
      final state = await getVehicleState();
      if (state == targetState) return true;
      await Future.delayed(interval);
    }
    return false;
  }

  /// Query scooter health from Redis.
  Future<ScooterHealth> queryHealth() async {
    final health = ScooterHealth();
    health.auxCharge = int.tryParse(
      await redisHget('aux-battery', 'charge') ?? '',
    );
    health.auxVoltageMv = int.tryParse(
      await redisHget('aux-battery', 'voltage') ?? '',
    );
    health.cbbStateOfHealth = int.tryParse(
      await redisHget('cb-battery', 'state-of-health') ?? '',
    );
    health.cbbCharge = int.tryParse(
      await redisHget('cb-battery', 'charge') ?? '',
    );
    // Stock and Librescoot both keep the CBB under this key. `false` is the
    // pack reporting itself absent, which is a different answer from the
    // charge fields being unreadable.
    final cbbPresent = await redisHget('cb-battery', 'present');
    if (cbbPresent == 'true' || cbbPresent == 'false') {
      health.cbbPresent = cbbPresent == 'true';
    }
    // battery-service owns this key and is absent from the bootstrap image, so
    // a missing answer means nobody could say rather than no pack fitted.
    final batteryPresent = await redisHget('battery:0', 'present');
    if (batteryPresent == 'true' || batteryPresent == 'false') {
      health.batteryPresent = batteryPresent == 'true';
    }
    health.batteryCharge = int.tryParse(
      await redisHget('battery:0', 'charge') ?? '',
    );
    return health;
  }

  /// Open the seatbox.
  Future<void> openSeatbox() async {
    await redisLpush('scooter:seatbox', 'open');
  }

  /// Turn the main battery off without touching the seatbox, by telling
  /// battery-service the latch is open. It answers by opening the pack's BMS
  /// contactors, which is electrically what lifting the pack out would do.
  ///
  /// vehicle-service is stopped first because it owns the real latch state and
  /// would re-assert `closed` on its next publish, re-activating the pack
  /// under us. It comes back on the reboot into UMS, which is moments away.
  ///
  /// The value has to be exactly `open` or `closed`: the stock C parser
  /// rejects anything else.
  Future<void> deactivateMainBattery() async {
    await runCommand(
      'systemctl stop unu-vehicle librescoot-vehicle 2>/dev/null; true',
    );
    await runCommand(
      "redis-cli hset vehicle seatbox:lock open >/dev/null && "
      "redis-cli publish vehicle seatbox:lock >/dev/null",
    );
  }

  /// Undo [deactivateMainBattery]. battery-service is what opens and closes the
  /// contactors: it subscribes to `vehicle seatbox:lock` and gates on the hash
  /// field (battery-service service.go:163, reader.go:122), so saying the latch
  /// is closed again is what brings the pack back.
  ///
  /// vehicle-service is restarted because we stopped it, and it owns the real
  /// latch and the dashboard the trampoline later drives. It is not the thing
  /// that switches the pack.
  Future<void> reactivateMainBattery() async {
    await runCommand(
      "redis-cli hset vehicle seatbox:lock closed >/dev/null; "
      "redis-cli publish vehicle seatbox:lock >/dev/null; true",
    );
    await runCommand(
      'systemctl start unu-vehicle librescoot-vehicle 2>/dev/null; true',
    );
  }

  /// Whether the main pack still has its contactors closed. `present` stays
  /// true throughout, because the pack never went anywhere.
  Future<bool> isMainBatteryActive() async {
    final state = await redisHget('battery:0', 'state');
    return state == 'active';
  }

  /// Check if CBB is connected.
  Future<bool> isCbbPresent() async {
    final present = await redisHget('cb-battery', 'present');
    return present == 'true';
  }

  /// Check if main battery is present.
  Future<bool> isBatteryPresent() async {
    final present = await redisHget('battery:0', 'present');
    return present == 'true';
  }

  /// Download a remote file's contents via cat. Returns null if the file doesn't exist.
  Future<Uint8List?> downloadFile(String remotePath) async {
    await _ensureConnected('file download');
    SSHSession? session;
    try {
      session = await _requireClient(
        'file download',
      ).execute('cat ${_shellEscape(remotePath)}');
      final chunks = <int>[];
      final stdoutDone = () async {
        await for (final data in session!.stdout) {
          chunks.addAll(data);
        }
      }();
      // Must drain stderr to prevent the session from blocking
      final stderrDone = () async {
        await for (final _ in session!.stderr) {}
      }();
      await Future.wait([
        stdoutDone,
        stderrDone,
        session.done,
      ]).timeout(const Duration(seconds: 30));
      if (session.exitCode != 0) return null;
      return Uint8List.fromList(chunks);
    } catch (_) {
      // Swallowing the error is deliberate (a missing file is a null), but the
      // session has to go regardless: a timeout here otherwise leaks a channel
      // per attempt.
      session?.close();
      return null;
    }
  }

  /// List files in a remote directory. Returns empty list if directory doesn't exist.
  Future<List<String>> listRemoteDir(String remotePath) async {
    try {
      final output = await runCommand(
        'ls -1 ${_shellEscape(remotePath)} 2>/dev/null',
      );
      return output.trim().split('\n').where((l) => l.isNotEmpty).toList();
    } catch (_) {
      return [];
    }
  }

  static String _shellEscape(String s) => "'${s.replaceAll("'", "'\\''")}'";

  /// Back up radio-gaga config from the MDB to a local directory.
  /// Checks both Librescoot (/data/radio-gaga/) and stock (/etc/rescoot/) paths.
  /// Returns the backup directory path, or null if no config was found.
  Future<String?> backupRadioGagaConfig(String backupBaseDir) async {
    final timestamp = DateTime.now()
        .toIso8601String()
        .replaceAll(':', '-')
        .split('.')
        .first;
    final backupDir = Directory(
      path.join(backupBaseDir, 'radio-gaga-backup-$timestamp'),
    );

    var found = false;

    // Librescoot path: /data/radio-gaga/config.yaml + any referenced certs
    final lsConfig = await downloadFile('/data/radio-gaga/config.yaml');
    if (lsConfig != null && lsConfig.isNotEmpty) {
      final targetDir = Directory(path.join(backupDir.path, 'data-radio-gaga'));
      await targetDir.create(recursive: true);
      await File(
        path.join(targetDir.path, 'config.yaml'),
      ).writeAsBytes(lsConfig);
      debugPrint('SSH: backed up /data/radio-gaga/config.yaml');
      found = true;

      // Also back up any referenced cert files
      try {
        final yamlStr = utf8.decode(lsConfig);
        final yaml = loadYaml(yamlStr);
        if (yaml is Map) {
          final mqtt = yaml['mqtt'];
          if (mqtt is Map) {
            final caCertPath = mqtt['ca_cert'] as String?;
            if (caCertPath != null && caCertPath.isNotEmpty) {
              final certData = await downloadFile(caCertPath);
              if (certData != null && certData.isNotEmpty) {
                final certFilename = path.basename(caCertPath);
                await File(
                  path.join(targetDir.path, certFilename),
                ).writeAsBytes(certData);
                debugPrint('SSH: backed up CA cert $caCertPath');
              }
            }
          }
        }
      } catch (e) {
        debugPrint('SSH: failed to parse LS config for cert paths: $e');
      }
    }

    // Stock scooterOS paths
    const stockPaths = [
      '/etc/rescoot/radio-gaga.yml',
      '/home/root/radio-gaga/radio-gaga.yml',
    ];
    for (final stockPath in stockPaths) {
      final stockConfig = await downloadFile(stockPath);
      if (stockConfig == null || stockConfig.isEmpty) continue;

      final targetDir = Directory(path.join(backupDir.path, 'etc-rescoot'));
      await targetDir.create(recursive: true);
      await File(
        path.join(targetDir.path, 'radio-gaga.yml'),
      ).writeAsBytes(stockConfig);
      debugPrint('SSH: backed up $stockPath');
      found = true;

      // Parse YAML to find referenced files (e.g. mqtt.ca_cert) and back those up too
      try {
        final yamlStr = utf8.decode(stockConfig);
        final yaml = loadYaml(yamlStr);
        if (yaml is Map) {
          final mqtt = yaml['mqtt'];
          if (mqtt is Map) {
            final caCertPath = mqtt['ca_cert'] as String?;
            if (caCertPath != null && caCertPath.isNotEmpty) {
              final certData = await downloadFile(caCertPath);
              if (certData != null && certData.isNotEmpty) {
                final certFilename = path.basename(caCertPath);
                await File(
                  path.join(targetDir.path, certFilename),
                ).writeAsBytes(certData);
                debugPrint('SSH: backed up CA cert $caCertPath');
              }
            }
          }
        }
      } catch (e) {
        debugPrint('SSH: failed to parse stock config for cert paths: $e');
      }
      break; // found one, no need to check others
    }

    if (!found) {
      debugPrint('SSH: no radio-gaga config found to back up');
      return null;
    }

    debugPrint('SSH: radio-gaga config backed up to ${backupDir.path}');
    return backupDir.path;
  }

  /// Restore a backed-up radio-gaga config to /data/radio-gaga/ on the MDB.
  /// Handles stock configs by rewriting ca_cert paths to /data/radio-gaga/.
  Future<bool> restoreRadioGagaConfig(String backupPath) async {
    final backupDir = Directory(backupPath);
    if (!await backupDir.exists()) return false;

    await runCommand('mkdir -p /data/radio-gaga');

    // Prefer Librescoot backup (already in the right format)
    final librescootDir = Directory(path.join(backupPath, 'data-radio-gaga'));
    if (await librescootDir.exists()) {
      for (final file in await librescootDir.list().toList()) {
        if (file is! File) continue;
        final filename = path.basename(file.path);
        final data = await file.readAsBytes();
        await uploadFile(
          Uint8List.fromList(data),
          '/data/radio-gaga/$filename',
        );
        debugPrint('SSH: restored /data/radio-gaga/$filename');
      }
      return true;
    }

    // Stock backup: needs path rewriting
    final stockDir = Directory(path.join(backupPath, 'etc-rescoot'));
    if (!await stockDir.exists()) return false;

    final configFile = File(path.join(stockDir.path, 'radio-gaga.yml'));
    if (!await configFile.exists()) return false;

    // Upload any non-YAML files first (certs, keys)
    for (final file in await stockDir.list().toList()) {
      if (file is! File) continue;
      final filename = path.basename(file.path);
      if (filename == 'radio-gaga.yml') continue;
      final data = await file.readAsBytes();
      await uploadFile(Uint8List.fromList(data), '/data/radio-gaga/$filename');
      debugPrint('SSH: restored /data/radio-gaga/$filename');
    }

    // Rewrite ca_cert path in the config and upload
    var configContent = await configFile.readAsString();
    try {
      final yaml = loadYaml(configContent);
      if (yaml is Map) {
        final mqtt = yaml['mqtt'];
        if (mqtt is Map) {
          final caCertPath = mqtt['ca_cert'] as String?;
          if (caCertPath != null && caCertPath.isNotEmpty) {
            final certFilename = path.basename(caCertPath);
            final newPath = '/data/radio-gaga/$certFilename';
            configContent = configContent.replaceAll(caCertPath, newPath);
            debugPrint('SSH: rewrote ca_cert path: $caCertPath → $newPath');
          }
        }
      }
    } catch (e) {
      debugPrint(
        'SSH: failed to rewrite cert paths, uploading config as-is: $e',
      );
    }

    await uploadFile(
      Uint8List.fromList(utf8.encode(configContent)),
      '/data/radio-gaga/config.yaml',
    );
    debugPrint(
      'SSH: restored /data/radio-gaga/config.yaml (converted from stock)',
    );
    return true;
  }

  /// Read the trampoline status file from MDB.
  Future<TrampolineStatus> readTrampolineStatus({String? expectedRunId}) async {
    try {
      TrampolineStatus? matchingStatus;
      final content = await runCommand(
        'cat /data/installer/trampoline-status 2>/dev/null',
      );
      if (content.trim().isNotEmpty) {
        final status = TrampolineStatus.parse(content);
        if (expectedRunId == null || status.runId == expectedRunId) {
          if (status.result != TrampolineResult.running &&
              status.result != TrampolineResult.unknown) {
            return status;
          }
          matchingStatus = status;
        }
      }

      final currentState = await runCommand(
        'cat $installerRunState 2>/dev/null || '
        'cat $legacyRunState 2>/dev/null; true',
      );
      if (currentState.trim().isNotEmpty) {
        final state = InstallRunState.parse(currentState);
        if (expectedRunId == null || state.runId == expectedRunId) {
          return state.toTrampolineStatus();
        }
      }
      if (matchingStatus != null) return matchingStatus;

      // The status file lives in the staging directory, and a device that
      // finished the install on its own sweeps that directory as its last act.
      // Its completion record is what survives, and a run that got far enough
      // to write one is a run that succeeded.
      final record = await runCommand(
        'cat $installerLastInstall 2>/dev/null || '
        'cat $legacyLastInstall 2>/dev/null',
      );
      if (record.trim().isNotEmpty) {
        final status = TrampolineStatus.parseCompletionRecord(record);
        if (expectedRunId == null) {
          if (status.result == TrampolineResult.success) return status;
        } else if (status.completedFor(expectedRunId)) {
          return status;
        }
      }
      return TrampolineStatus(result: TrampolineResult.unknown);
    } catch (_) {
      return TrampolineStatus(result: TrampolineResult.unknown);
    }
  }

  /// The run-state file both sides write: which stage the run reached, who
  /// wrote it last, and whether it ended. Null when the board has none.
  Future<InstallRunState?> readInstallRunState() async {
    try {
      final content = await runCommand(
        'cat $installerRunState 2>/dev/null || '
        'cat $legacyRunState 2>/dev/null; true',
      );
      if (content.trim().isEmpty) return null;
      return InstallRunState.parse(content);
    } catch (_) {
      return null;
    }
  }

  /// Whether a trampoline is running on the board right now.
  ///
  /// The state file says what the last write claimed, which is not the same
  /// thing: a run killed mid-stage leaves "running" behind forever. Only the
  /// process answers the question the caller is actually asking.
  Future<bool> trampolineAlive() async {
    try {
      final out = await runCommand(
        'pgrep -f "/data/(installer/(scripts/)?)?trampoline.sh" '
        '>/dev/null && echo yes || echo no',
      ).timeout(const Duration(seconds: 10));
      return out.trim().endsWith('yes');
    } catch (_) {
      return false;
    }
  }

  /// The tail of the trampoline's own log, which is the only account of what
  /// happened while the laptop was unplugged.
  Future<String> readTrampolineLogTail({int lines = 40}) async {
    try {
      final out = await runCommand(
        'tail -n $lines /data/installer/trampoline.log 2>/dev/null; true',
      ).timeout(const Duration(seconds: 20));
      return out.trimRight();
    } catch (_) {
      return '';
    }
  }


  Future<void> writeInstallRunState({
    required String runId,
    required String content,
  }) async {
    if (!RegExp(r'^[a-zA-Z0-9._-]+$').hasMatch(runId)) {
      throw ArgumentError.value(runId, 'runId', 'contains unsafe characters');
    }
    final runDir = '$installerHistoryDir/$runId';
    final historyPath = '$runDir/record';
    final historyTemp = '$runDir/.record.tmp';
    final currentTemp = '$installerDir/.run-state.$runId.tmp';
    await runCommand('mkdir -p $runDir');
    await uploadFile(Uint8List.fromList(utf8.encode(content)), historyTemp);
    await runCommand(
      'mv -f $historyTemp $historyPath; '
      'cp $historyPath $currentTemp; '
      'mv -f $currentTemp $installerRunState',
    );
  }
}
